---
- hosts: all
  tasks:
  - name: install convenient packages
    yum: state=present name={{item}}
    with_items:
      - bash-completion
      - net-tools
      - bind-utils
      - vim
      - telnet
    become: true
    become_method: sudo
